Repository ZEISS/acme-dns-azure, pull requests merged in 2024-03, with the labels that each got.

#92 use absolute path
  acme_dns_azure/___init___.py
Labels: patch

#94 fix reference
  acme_dns_azure/certbot_manager.py
Labels: patch

#96 Test/app build
  .github/workflows/azure_function.yml
  README.md
  acme_dns_azure/config/schema.py
  examples/function/pyproject.toml
Labels: prerelease

#98 remove linebreaks
  examples/function/function_app.py
Labels: patch

#102 Feature/support cname lookup
  .gitignore
  README.md
  acme_dns_azure/certbot_manager.py
  acme_dns_azure/config/schema.py
  acme_dns_azure/dns_delegation.py
  examples/README.md
  poetry.lock
  pyproject.toml
  tests/app/resources/certbot_init/expected_certbot_dns_azure.ini
  tests/app/resources/config/accepted.yaml
  tests/app/resources/config/accepted_additional_certbot_ini_params.yaml
  tests/app/resources/config/not_accepted_additional_param.yaml
  tests/app/resources/config/not_accepted_wrong_web_ref.yaml
  tests/app/test_certbot_manager.py
  tests/integration/README.md
  tests/integration/conftest.py
  tests/integration/happy_path.py
  tests/integration/helper_framework/acme_config_manager.py
  tests/integration/helper_framework/azure_ad_manager.py
  tests/integration/helper_framework/azure_dns_zone_manager.py
  tests/integration/helper_framework/azure_key_vault_manager.py
  tests/integration/infra/outputs.tf
  tests/integration/unhappy_path.py
Labels: minor
